on:
  push:
    tags:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  test1:
    runs-on: ubuntu-latest
    name: Helm Kubeval Action test 1.21.6
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: helm kubeval 1.21.6
        uses: ./ # Uses an action in the root directory
        with:
          path: 'test/charts'
          version: 1.21.6
          ignore_missing_schemas: false
  test2:
    runs-on: ubuntu-latest
    name: Helm Kubeval Action test 1.19.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: helm kubeval 1.19.0
        uses: ./ # Uses an action in the root directory
        with:
          path: 'test/charts'
          version: 1.19.0
          ignore_missing_schemas: false
   test3:
    runs-on: ubuntu-latest
<<<<<<< HEAD
    name: Helm Kubeval Action test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: helm kubeval single chart
=======
    name: Helm Kubeval Action test single chart
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: helm kubeval
>>>>>>> edit test workflow & test2 single chart test
        uses: ./ # Uses an action in the root directory
        with:
          path: 'test2'
          version: 1.21.6
          ignore_missing_schemas: false
